### ISSUE TITLE
Enlace de al canal de chat

### ISSUE THREAD

**Issue by nekopq** [AppLibresInstaReport/InstaReport#13]
Enlace para entrar al canal de chat
https://discord.gg/0mFyzzyfb8qKLHhk

El bot a usar: https://github.com/chalda/DiscordBot

**Comment by ricrojas** [comment]
Esto ya ha sido hecho. Agregué un enlace al bot en el [Home](https://github.com/AppLibresInstaReport/InstaReport/wiki) de la wiki. Será necesario agregar otro en la [Guía de Uso de Discord](https://github.com/AppLibresInstaReport/InstaReport/wiki/Guia-de-Uso-Discord)?

**Comment by nekopq** [comment]
@ricrojas creo que solo sería como información que usamos ese proyecto para nuestro bot, creo que si sería bueno ponerlo ahi también.
