### ISSUE TITLE
Aplicación para encuestas

### ISSUE THREAD

**Issue by nekopq** [AppLibresInstaReport/InstaReport#16]
Para decidir sobre puntos necesarios vamos a usar una aplicación, sugiero estas:
http://www.tricider.com/
Google Forms
Si alguien más tiene alguna idea, es bienvenida
@ricrojas @jonathanQuinchiguango Pueden hacerse cargo de implementar la aplicación una vez escogida?

**Comment by jonathanQuinchiguango** [comment]
ya me registre. Pero creo que es necesario que todos se inscriban?

**Comment by ricrojas** [comment]
Ya estoy utilizando tricider. Cada que haya algún punto en qué votar o aportar ideas, se debe crerar una nueva encuesta.

**Comment by ricrojas** [comment]
Encuesta de ejemplo: agreguen ideas para ver qué tal va http://www.tricider.com/brainstorming/35caoqtsuO7

**Comment by Santiagobssi** [comment]
@jonathanQuinchiguango ya escribí mi idea y al parecer no es necesario registrarte, ya que ofrece la opción de escribirla sin registrarte.....

**Comment by ricrojas** [comment]
@fercho1 por qué cerraste el issue? Todavía no hemos llegado a un acuerdo de qué herramienta usar.
