### ISSUE TITLE
Elaboración del tutorial de Cómo Usar la Aplicación

### ISSUE THREAD

**Issue by jonathanQuinchiguango** [AppLibresInstaReport/InstaReport#19]
Muchachos quien va hacer el tutorial de cómo usar la aplicación @nekopq  @ricrojas  @Santiagobssi

**Comment by ricrojas** [comment]
¿Cuál aplicación? Si te refieres a Github, ya tenemos una descripción de los labels y una guía de suscripción (ambos en los wikis). Falta la guía para reportar un bug. 
Si te refieres a las aplicaciones que usamos para hacer seguimiento al proyecto, @nekopq ya escribió guías para Trello y para Discord, igualmente en los wikis.

**Comment by jonathanQuinchiguango** [comment]
Me refería a como utilizar la aplicación final del proyecto, es decir indicar como generar los diferentes gráficos.

**Comment by nekopq** [comment]
ya está el tutorial en el sitio web
