### ISSUE TITLE
Correos Electronicos para editar el Diseño

### ISSUE THREAD

**Issue by fercho1** [AppLibresInstaReport/InstaReport#2]
@nekopq , @ricrojas , @jonathanQuinchiguango Por favor enviar los correos para editar el Diseño de InstaReport en Google Drive

**Comment by nekopq** [comment]
nekopq@gmail.com

**Comment by jonathanQuinchiguango** [comment]
jon.javi08epn@gmail.com

**Comment by fercho1** [comment]
Gracias muchacho comienzen a editar el diseño ya les agregue y el link es https://docs.google.com/drawings/d/11yn8HgUvSDkZSCOJQ7Jnu2I1_1omTAsVYwOGVedjQqU/edit
