### ISSUE TITLE
Comandos para el bot de Discord

### ISSUE THREAD

**Issue by nekopq** [AppLibresInstaReport/InstaReport#20]
El bot cuenta con el comando !ayuda, este comando debe ser ingresado seguido de la pregunta que se tenga.

Ejemplo: "!ayuda como suscribirme?"

La pregunta al lado del comando se divide en palabras clave y según éstas, el bot responderá. Las palabras clave que el bot puede responder son:
- -suscrib (suscribirme, suscribo, suscripción, etc)
- -info (info, informacion, información, etc)
- -ayuda
- -descarg (descargar, descargo, etc)
- -baj (bajar, bajo, etc)
- -uso, usar, entrar
- -error
- -problema

**¿qué otras palabras clave debería responder el bot?**

@fercho1 @ricrojas @Santiagobssi @jonathanQuinchiguango 

.

**Comment by ricrojas** [comment]
Por lo que veo está bien. Talvez algo que responda a las palabras "problema", "error", o cosas parecidas. La respuesta debería decir "Envíenos la descripción de su problema a email@instareport.example" o algo parecido.

**Comment by nekopq** [comment]
Palabras clave problema y error añadidas

**Comment by Santiagobssi** [comment]
Considero que las palabras que indican son las más importantes, pero en vez de "!ayuda" podríamos poner "ayuda!", ya que regularmente se suele utilizar más el signo de admiración al final de la palabra...

**Comment by jonathanQuinchiguango** [comment]
si no estoy mal @Santiagobssi  el "!ayuda" es un comando de bot, eso no creo que se puede cambiar, las palabras claves siguientes si se las puede cambiar. ¿Es verdad o no @nekopq ?

**Comment by ricrojas** [comment]
Sí, los comandos del bot inician con el símbolo '!'
