### ISSUE TITLE
Edición del Logo

### ISSUE THREAD

**Issue by nekopq** [AppLibresInstaReport/InstaReport#3]
¿Qué podríamos cambiar del logo? ya sea los colores, diseño general. Dejen sus comentarios

**Comment by jonathanQuinchiguango** [comment]
El logo esta bien, por mi parte no creo que este de cambiarlo

**Comment by fercho1** [comment]
Pienso que tambié esta bien el logo

**Comment by Santiagobssi** [comment]
Está full bien elaborado! Considero que no se debe modificarlo.
