### ISSUE TITLE
Lista de correos

### ISSUE THREAD

**Issue by ricrojas** [AppLibresInstaReport/InstaReport#4]
¿Cómo vamos a hacer la lista de correos? Se supone que es algo en lo que ya deberíamos estar trabajando. 
Buscando en la web, encontré que quizás la forma más fácil de hacerlo es con [Grupos de Google.](https://groups.google.com/forum/#!overview)
Hay también otras opciones como [Mailchimp](http://mailchimp.com/), [Mailman](http://www.gnu.org/software/mailman/), etc.
¿Cuál de las alternativas escogemos? Si tienen otras propuestas, adelante!

**Comment by jonathanQuinchiguango** [comment]
Yo igual estaba viendo, y pienso que lo más conveniente seria con Grupos de Google,pero tocaría ver lo que diga el Ing.

**Comment by fercho1** [comment]
Muchachos yo ya Utilize Mailchimp y esta exelnete ya hize pruebas también y si funciona

**Comment by ricrojas** [comment]
No se debería cerrar este issue hasta que tengamos funcionando la lista de correos. Por el momento solo sabemos que lo probaste [Fernando](@fercho1), pero nadie más es testigo de ello. Sería bueno si haces una lista de correos para que nos suscribamos los contribuidores del proyecto.

**Comment by Santiagobssi** [comment]
Mañana podríamos probar cuál de los dos nos ofrece mayor completitud con lo que necesitamos, porque al igual que Jonathan consideraba usar Grupos de Google....

**Comment by ricrojas** [comment]
La discusión sigue en #6
