### ISSUE TITLE
URL del Diseño del Proyecto InstaReport

### ISSUE THREAD

**Issue by fercho1** [AppLibresInstaReport/InstaReport#5]
https://docs.google.com/drawings/d/11yn8HgUvSDkZSCOJQ7Jnu2I1_1omTAsVYwOGVedjQqU/edit?usp=sharing

**Comment by jonathanQuinchiguango** [comment]
Muchachos solo vamos a tener una interfaz, porque creo que con esa interfaz solo servirá para reportes individuales, en cambio si queremos crear un reporte del curso no hay como hacerlo, una solución para no crear otra interfaz seria, agregarle a esa misma interfaz más funcionalidades, ¿Qué dicen muchachos?

**Comment by ricrojas** [comment]
Probablemente una pantalla sea suficiente, pero habría que poner las opciones de 
- Reportar por prueba, 
- Reportar por estudiante,
- Reportar por curso (si es que se pone eso en el modelo),
- etc. 

Tenemos además que acordar qué se mostrará en cada 'tipo' de reporte que decidamos mostrar.

**Comment by jonathanQuinchiguango** [comment]
Muchachos ya realice algunos cambios a la interfaz para que nos genere diferentes tipos de reportes, ahí le revisan para ver si esta bien.
