### ISSUE TITLE
URL del formulario para que se registren (Utilizando MailChimp)

### ISSUE THREAD

**Issue by fercho1** [AppLibresInstaReport/InstaReport#6]
http://eepurl.com/bCXZtX

**Comment by nekopq** [comment]
Al final del formulario aparece tu dirección, no de correo, de tu casa. Revísale si le puedes quitar

**Comment by jonathanQuinchiguango** [comment]
@fercho1 ya revisaste lo que menciona @nekopq

**Comment by Santiagobssi** [comment]
En la lista de suscriptores que planteaste, ¿existe la posibilidad de elegir el tipo de suscripción?

**Comment by ricrojas** [comment]
De lo que dice @Santiagobssi, deberían haber al menos dos tipos de suscripción: 
- una para colaboradores (reciben todos los correos),
- y otra de usuarios (reciben correos de releases, bugs solucionados, otra información importante).

Si alguien tiene otra idea, planteen, y acordemos quién hace. Lo más óptimo sería que @fercho1 añada esas opciones.

**Comment by jonathanQuinchiguango** [comment]
Creo que con esos dos tipos son suficientes
