### ISSUE TITLE
Guía de como suscribirse al proyecto

### ISSUE THREAD

**Issue by jonathanQuinchiguango** [AppLibresInstaReport/InstaReport#9]
Compañeros una pregunta ¿Como debemos hacer la guía para suscribirse al proyecto?,

**Comment by ricrojas** [comment]
Habría que esperar a que @fercho1 haga las dos opciones de suscripción en la lista de correos, pero podemos comenzar haciendo un borrador mientras tanto.

**Comment by jonathanQuinchiguango** [comment]
Ya pero hay que hacer un documento  y anexarlo, o describir los pasos uno por uno en la página y en el  readme

**Comment by ricrojas** [comment]
Ya hice algo mientras Fernando nos da los enlaces verdaderos de suscripción https://github.com/AppLibresInstaReport/InstaReport#suscríbete

**Comment by jonathanQuinchiguango** [comment]
@ricrojas tu guía ya le agregue a la página web

**Comment by fercho1** [comment]
Muchachos Ya puse los links para los subscriptores: colaboradores y usuarios: La guía sería ir a los links y llenarlos

**Comment by ricrojas** [comment]
dónde pusiste?

**Comment by nekopq** [comment]
@ricrojas está en la página web
